travis:
  secure:
    BINSTAR_TOKEN: at5yweOPbH80R9qesLpSfFuWGJelZa7ADzWHh5t2QD8DpmVdpIKDuMkERGfHTv550fxfFg1IzSub3M2bGxFA16y7w8MwnsVMeh8VvkGW18kVvzKD2oeXx3NH9qMgcvSq7HJLuFWZ1ea9fEHk2ieThrHguiEoLO6lZgb3YzT+aD7zgMCkfR/u/4rGvvH/nydiahfMZt5h5M8ohY5SHiqWHYXZ5u5o0uSBuIFXM+mw/SE2v8hfYVOAcwGSypEYpDRgw8hHTBxaAFAFZbe03Ypg1zgdiBhQt+NfEPuYsigOVK4dmdDZ2Un3TQzOEMJ5O6ROEOBLqjXj5AD27ZAvCJPEsk+vK7Cj7lAksY1nY1FK5A29AyfkoKkJoVFDhQSpAGWV0hNXFRQDpMBE5geiEEFLE/D3rC3QAqRFhOs/wbe72Inxy8xPdJZueIvMCTbqDNw6S/ryO/YpbwlvtYeasmDu4Ft3yhW7VYc0T/d9FO/IgOMsWvfq3zMtpqd1XUhVIUpF0Q/BFz2nf97/iT0KRFmA5+b4Iu7iqRm6vQtGWnn0e8zwoh4x6sbVLI8P/xxlFhQ9Z38CZRaEEe7bRDIBlq3e6f0flvDCEZMFavDJATgtNRf5PtNKegFJ9h/s9lunBu/j807arqgJ25BKOdULAAmD3pYY4nkd/uIb/MMWzvtbAeI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
