travis:
  secure:
    BINSTAR_TOKEN: cxJUvNvokIpahviMYDPsQVvhZFKFSdtL5qvCOLKE7laecfETqLmzHRBHTmCDTxjoN5P2eo/5mj8ENdk9pwpK4HD8hRqkekMUM2lrT4e9SgRjrWrF8eS6kQAyeU3rt9IH5kBBfsXH9rZivZz5OaR+Qa5GddGk4T1EuCfRV7BRXnCYNSNktdiTIHLeZkX8meiyhuFVrs2s+7Fskzc9eo+Hd8KDTqmTrqUKzr8ibxtBJDwqwmTmeIaWhQCk2pROAMmcn6bzeni/2X74Ewna5xkt9QSVJZfHkO+id49PY2fo7ndIV/mgpKzsI8tKAl6win6+Hd+otcbUsJV2Mz6i0Qy92d/TjWpf00suPhAld8xAS9CtJ2GMlTGW9T8ZsLVwPk+UmbPJU+lMY3pUq6irkRH9XVEVGZqnCyNyu0ldyC3amD3bbDMeIs0TP0w1pM4ItcwnimQfXd8EQkw85SCTM+dRwxJ7i5bR8utdgKlKYHE2MYak9vK6w33CxhdDESZff+5nu32ZaPx/1DoUYnedv44H/UH5vmOH0Yz1VVb0FgtDwRwlow8A9nQI+WRN8eJROFQl8nQAr99GRi6UvMjQpcntgPJWSWY17ho0WzPIB5133TwLVvy8Lf/ioUTqvxr6ZlhwSc99sR3oAdBTS8SYNvI7sblb8nRL/xjUU4lE9IdPNRI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
